//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.23 at 06:20:59 PM OMST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geekbrains.ru/marchmarker/categories", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.geekbrains.marchmarker.soap.categories;
